site_name: Byte Mind

site_url: 

use_directory_urls: False

theme:
  name: material
  palette:
    primary: black
    schema: slate

  font:
    text: Noto Serif
    code: Roboto Mono

  features:
    - toc.integrate
    - navigation.tabs
    # - navigation.tabs.sticky

nav:
  - Blog:
    - blog/index.md

plugins:
  - blog
  - social
  - tags:
      tags_file: blog/tags.md

markdown_extensions:
  - admonition # add call-out blocks